apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      name: mysql
  type: NodePort
  selector:
    app: mysql
